api_url = "http://192.168.1.203:21727"

[credentials]
cas = ""
pronote_url = ""
username = ""
password = ""

[webhook]
lesson_add = ""
lesson_edit = ""
lesson_cancel = ""
lesson_away = ""
note_add = ""
info_add = ""